[package]
name = "wasm_benches"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"

